"""Property-based test for serialization round-trip fidelity.

# Feature: nlp-feedback-routing, Property 16

**Validates: Requirements 23.6**

Property 16: Serialization Round-Trip Fidelity — For any valid FeedbackAnalysis
record, serializing to JSON and then deserializing from that JSON SHALL produce
a record where every field value is identical to the original, including
floating-point values within 6-decimal-digit precision.
"""

from __future__ import annotations

from hypothesis import given, settings

from nlp_processing.models.feedback_routing import FeedbackAnalysis
from nlp_processing.serialization.feedback_serializer import (
    FeedbackAnalysisSerializer,
)
from tests.feedback_routing.strategies import feedback_analysis_records


@given(record=feedback_analysis_records())
@settings(max_examples=100)
def test_serialize_deserialize_roundtrip_fidelity(record: FeedbackAnalysis) -> None:
    """Verify serialize → deserialize produces an identical FeedbackAnalysis record.

    # Feature: nlp-feedback-routing, Property 16
    **Validates: Requirements 23.6**

    For any valid FeedbackAnalysis record generated by Hypothesis, the
    round-trip through FeedbackAnalysisSerializer.serialize() followed by
    FeedbackAnalysisSerializer.deserialize() must produce a record where:
    - All string fields are exactly equal
    - All boolean fields are exactly equal
    - All optional fields (None vs value) are preserved
    - All float fields are equal within 6-decimal precision (1e-6 tolerance)
    - Entity lists preserve order, count, and field values
    """
    serializer = FeedbackAnalysisSerializer()

    # Serialize to JSON
    json_str = serializer.serialize(record)

    # Deserialize back
    restored = serializer.deserialize(json_str)

    # Verify string fields are identical
    assert restored.feedback_id == record.feedback_id, (
        f"feedback_id mismatch: {restored.feedback_id!r} != {record.feedback_id!r}"
    )
    assert restored.sentiment_label == record.sentiment_label, (
        f"sentiment_label mismatch: {restored.sentiment_label!r} != {record.sentiment_label!r}"
    )
    assert restored.priority_level == record.priority_level, (
        f"priority_level mismatch: {restored.priority_level!r} != {record.priority_level!r}"
    )
    assert restored.theme_primary == record.theme_primary, (
        f"theme_primary mismatch: {restored.theme_primary!r} != {record.theme_primary!r}"
    )
    assert restored.theme_secondary == record.theme_secondary, (
        f"theme_secondary mismatch: {restored.theme_secondary!r} != {record.theme_secondary!r}"
    )
    assert restored.intent == record.intent, (
        f"intent mismatch: {restored.intent!r} != {record.intent!r}"
    )
    assert restored.cluster_id == record.cluster_id, (
        f"cluster_id mismatch: {restored.cluster_id!r} != {record.cluster_id!r}"
    )
    assert restored.processed_at == record.processed_at, (
        f"processed_at mismatch: {restored.processed_at!r} != {record.processed_at!r}"
    )

    # Verify boolean fields
    assert restored.requires_action == record.requires_action, (
        f"requires_action mismatch: {restored.requires_action} != {record.requires_action}"
    )

    # Verify float fields within 6-decimal precision
    assert abs(restored.sentiment_score - round(record.sentiment_score, 6)) < 1e-6, (
        f"sentiment_score mismatch: {restored.sentiment_score} vs {record.sentiment_score} "
        f"(rounded: {round(record.sentiment_score, 6)})"
    )
    assert abs(restored.priority_score - round(record.priority_score, 6)) < 1e-6, (
        f"priority_score mismatch: {restored.priority_score} vs {record.priority_score} "
        f"(rounded: {round(record.priority_score, 6)})"
    )

    # Verify entities list
    assert len(restored.entities) == len(record.entities), (
        f"entities count mismatch: {len(restored.entities)} != {len(record.entities)}"
    )
    for i, (r_ent, o_ent) in enumerate(zip(restored.entities, record.entities)):
        assert r_ent.entity_type == o_ent.entity_type, (
            f"entities[{i}].entity_type mismatch: {r_ent.entity_type!r} != {o_ent.entity_type!r}"
        )
        assert r_ent.entity_value == o_ent.entity_value, (
            f"entities[{i}].entity_value mismatch: {r_ent.entity_value!r} != {o_ent.entity_value!r}"
        )
        assert abs(r_ent.confidence - round(o_ent.confidence, 6)) < 1e-6, (
            f"entities[{i}].confidence mismatch: {r_ent.confidence} vs {o_ent.confidence} "
            f"(rounded: {round(o_ent.confidence, 6)})"
        )
